# Generated by Django 5.0.2 on 2024-03-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes', '0003_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
