# Generated by Django 5.0.2 on 2024-03-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_likedrecipe'),
        ('receipes', '0007_alter_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedrecipe',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='receipes.recipe'),
        ),
    ]
