# Generated by Django 5.0.2 on 2024-03-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
